---
title: "Tarea 2"
author: "Matías Martínez"
date: "10 de mayo de 2018"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(tidyverse)
datos<- read.csv2("https://catalogodatos.gub.uy/dataset/fded3eeb-2904-43a5-a348-0b31434ef085/resource/d8ac0fb1-c972-4539-a889-bc510f999090/download/emisiones-de-co2-por-sector.csv",header=T,sep=";",stringsAsFactors=F,na.strings="unknown",fill=T)
d_emision<- gather(datos, key = fuente, value = emision, -AÑO)
```
## Ejercicio 1

1)
```{r}
d_emision %>% filter(!(fuente=="TOTAL" | fuente=="S_C" | fuente=="I_E")) %>% drop_na()%>% group_by(fuente,AÑO,emision) %>% group_by(fuente) %>% summarise(max=max(emision)) %>% arrange(desc(max)) %>% ggplot() + geom_bar(aes(reorder(fuente,-max),max),stat="identity")
```
 La Quema de Biomasa es la mayor fuente de emisiones de CO2 desde 2008 hasta 2016.
 
2)
```{r}
d_emision %>% filter(!(fuente=="TOTAL" | fuente=="S_C" | fuente=="I_E")) %>% drop_na()%>% filter(emision==max(emision))
```
Su año con emisión móxima fue el 2016, alcanzando 8831.


3)
```{r}
media=d_emision %>% filter(!(fuente=="TOTAL" | fuente=="S_C" | fuente=="I_E")) %>% drop_na() %>% group_by(fuente) %>%  summarise(media=mean(emision)) %>% arrange(desc(media)) %>% head(5)
media %>%  ggplot(aes(reorder(fuente,-media),media)) + geom_bar(stat="identity",aes(fill=fuente,colour=fuente),show.legend = FALSE) + 
  labs(x="Fuentes con mayor emisión media entre 1990 − 2016",y="Media de emisión en Gg",title="Gráfico de barras: media de emisiones de CO2 por fuente") 

d_emision %>% filter(!(fuente=="TOTAL" | fuente=="S_C" | fuente=="I_E")) %>% drop_na() %>% group_by(fuente) %>% ggplot(aes(reorder(fuente,-emision),emision)) + geom_boxplot() + geom_jitter(alpha=.2) + labs(x="Fuentes con mayor emisión media entre 1990−2016",y="Emisión de CO2 en Gg", title= "Diagrama de caja: emisión media por fuente")
```
4)
```{r}
d_emision %>% filter(fuente==(media$fuente)) %>% 
  drop_na() %>% ggplot(aes(AÑO,emision)) + 
  geom_line(aes(colour=fuente)) + geom_point(alpha=1/2) + 
  labs(x="Año desde 1990-2016",y="Emisión de CO2 en Gg",title="Gráfica series de tiempo: emisión de CO2 según fuente",caption=paste0(strwrap("Desde años ulteriores al 2000, la emisión producto de la quema de biomasa es creciente y año a año toma distancias mayores a las demás fuentes", 80), sep="", collapse="\n"))
```

5)

```{r}
d_emision %>% filter(fuente==(media$fuente)) %>% drop_na() %>% group_by(fuente) %>% ggplot(aes(reorder(fuente,-emision),emision)) + geom_boxplot()  + labs(x="Fuentes con mayor emisión media entre 1990−2016",y="Emisión de CO2 en Gg", title= "Diagrama de caja: emisión media por fuente")
```

6)

```{r}
library(ggpmisc)

d_emision %>% drop_na() %>% filter(fuente=="TOTAL") %>% ggplot(aes(AÑO,emision))+ geom_point() + geom_line()+ stat_peaks(colour = "red") + stat_peaks(geom = "text", colour = "red", hjust = -0.1) +labs(x="Año desde 1990-2016",y="Total de emisiones de CO2 en Gg", title="Gráfico series de tiempo: emisión total de CO2")
```


## Ejercicio 2

```{r}
med<- read.csv2("https://catalogodatos.gub.uy/dataset/96e636e5-4f78-49a7-8e14-60e90173a0c0/resource/936ac9e6-b0f6-424a-9b53-ee408a91fd6f/download/datos_gastos-por-actos-mdicos-2016.csv",header = TRUE,sep=",")
str(med)
```

Preguntas a responder:

1) ¿Cuál es la media de edad según sexo?

```{r}
table(med$Sexo)
med %>% drop_na() %>% select(Edad_años ,Sexo ) %>% ggplot(aes(Sexo,Edad_años)) + geom_boxplot(aes(fill=Sexo),show.legend = F) + labs(y="Edad en Años", title="Diagrama de caja: distriución edad según sexo")


med %>% drop_na() %>% select(Edad_años ,Sexo ) %>% ggplot(aes(Edad_años)) + geom_freqpoly(aes(colour=Sexo),binwidth = 2) + labs(x="Edad en Años",y="Frecuencia absoluta", title="Histograma: distriución edad según sexo")

```
2)
